#!/usr/local/bin/bash

# clean build directory
rm /Users/Joel/docs/project2/build/main.*

# generate figures
# nim c -r --verbosity:0 ./code/svg_generate.nim
python3 ./code/make-figures.py

# build commands
xelatex --shell-escape \\nonstopmode \\input main.tex
# pdflatex --shell-escape \\nonstopmode \\input main.tex
# makeindex -s main.ist -o main.gls main.glo
# echo "\@istfilename{main.ist}" >> main.aux
# makeglossaries main
# rm -Rf `biber --cache`
biber main
xelatex --shell-escape \\nonstopmode \\input main.tex
xelatex --shell-escape \\nonstopmode \\input main.tex

 mv *.spl *.log *.out *.toc *.aux *.bcf *.blg *.bbl *.run.xml ./log
