#!/usr/local/bin/bash

# clean build directory
rm /Users/Joel/docs/project2/build/main.*

# build commands

xelatex --shell-escape \\nonstopmode \\input main.tex
# pdflatex --shell-escape \\nonstopmode \\input main.tex
# makeindex -s main.ist -o main.gls main.glo
# echo "\@istfilename{main.ist}" >> main.aux
# makeglossaries main
biber main
xelatex --shell-escape \\nonstopmode \\input main.tex
xelatex --shell-escape \\nonstopmode \\input main.tex

# move output to build dir
mv *.ilg *.ind *.glg *.glo *.gls *.glsdefs *.ist *.log *.out *.toc *.aux *.pdf *.bcf *.blg *.bbl *.run.xml ./build
